#!/bin/bash
set -euo pipefail

# ============================================================
# MicroPython compile + deploy tool
#
# Workflow:
#   1. Configure paths and targets on first run (or after moving this script)
#   2. Choose whether to compile all .py files first
#   3. Select the files to deploy
#   4. Upload selected files and run mpremote remotely
#
# Dependencies:
#   - whiptail
#   - ssh
#   - scp
#   - mpy-cross
# ============================================================

ARCH="armv7emsp"

# ---------- helpers ----------------------------------------------------------

die() {
    echo "ERROR: $*" >&2
    exit 1
}

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "'$1' is required but was not found."
}

input_box() {
    local title="$1"
    local prompt="$2"
    local default="$3"

    whiptail --title "$title" \
        --inputbox "$prompt" 10 80 "$default" \
        3>&1 1>&2 2>&3
}

yes_no() {
    local title="$1"
    local prompt="$2"

    whiptail --title "$title" \
        --yesno "$prompt" 10 80
}

# ---------- dependency checks -----------------------------------------------

require_cmd whiptail
require_cmd ssh
require_cmd scp

# ---------- configuration ----------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The script lives in the project root, so use its folder as the default.
PROJECT_DIR_DEFAULT="$SCRIPT_DIR"
SOURCE_DIR_DEFAULT="$SCRIPT_DIR"
OUTPUT_DIR_DEFAULT="$SCRIPT_DIR/MPY"
MPY_CROSS_DEFAULT="$SCRIPT_DIR/mpy-cross"
SSH_TARGET_DEFAULT="pi@raspberry.local"
MPREMOTE_DEFAULT="mpremote"

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/serial-guardian"
CONFIG_FILE="$CONFIG_DIR/compile_deploy.conf"
CURRENT_SCRIPT_DIR="$SCRIPT_DIR"

save_config() {
    mkdir -p "$CONFIG_DIR"
    {
        printf 'SCRIPT_DIR=%q\n' "$SCRIPT_DIR"
        printf 'SOURCE_DIR=%q\n' "$SOURCE_DIR"
        printf 'OUTPUT_DIR=%q\n' "$OUTPUT_DIR"
        printf 'MPY_CROSS=%q\n' "$MPY_CROSS"
        printf 'SSH_TARGET=%q\n' "$SSH_TARGET"
        printf 'MPREMOTE=%q\n' "$MPREMOTE"
    } > "$CONFIG_FILE"
}

load_config() {
    [[ -f "$CONFIG_FILE" ]] || return 1
    # This file is generated by save_config and contains shell-quoted values.
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    [[ -n "${SCRIPT_DIR:-}" && -n "${SOURCE_DIR:-}" && -n "${OUTPUT_DIR:-}" &&
        -n "${MPY_CROSS:-}" && -n "${SSH_TARGET:-}" && -n "${MPREMOTE:-}" ]]
}

configure_all() {
    local source_default="$SOURCE_DIR_DEFAULT"
    local output_default="$OUTPUT_DIR_DEFAULT"
    local mpy_cross_default="$MPY_CROSS_DEFAULT"
    local ssh_target_default="$SSH_TARGET_DEFAULT"
    local mpremote_default="$MPREMOTE_DEFAULT"

    SOURCE_DIR="$(input_box \
        "Source folder" \
        "Folder containing the .py files to compile:" \
        "$source_default")" || return 1

    OUTPUT_DIR="$(input_box \
        "Output folder" \
        "Folder where the compiled .mpy files will be written:" \
        "$output_default")" || return 1

    MPY_CROSS="$(input_box \
        "mpy-cross" \
        "Path to the mpy-cross executable:" \
        "$mpy_cross_default")" || return 1

    SSH_TARGET="$(input_box \
        "SSH target" \
        "Remote SSH target (user@host):" \
        "$ssh_target_default")" || return 1

    MPREMOTE="$(input_box \
        "mpy remote command" \
        "Remote mpremote executable/command:" \
        "$mpremote_default")" || return 1
}

if ! load_config || [[ "${SCRIPT_DIR:-}" != "$CURRENT_SCRIPT_DIR" ]]; then
    SCRIPT_DIR="$CURRENT_SCRIPT_DIR"
    configure_all || {
        echo "Cancelled."
        exit 0
    }
    [[ -d "$SOURCE_DIR" ]] || die "Source directory does not exist: $SOURCE_DIR"
    [[ -x "$MPY_CROSS" ]] || die "mpy-cross is missing or not executable: $MPY_CROSS"
    save_config
else
    SCRIPT_DIR="$CURRENT_SCRIPT_DIR"
    [[ -d "$SOURCE_DIR" ]] || die "Source directory does not exist: $SOURCE_DIR"
    [[ -x "$MPY_CROSS" ]] || die "mpy-cross is missing or not executable: $MPY_CROSS"
fi

mkdir -p "$OUTPUT_DIR"

# ---------- main menu --------------------------------------------------------

while true; do
    MENU_CHOICE="$(
        whiptail --title "MicroPython Compile / Deploy" \
            --menu "Choose an operation:" 15 75 5 \
            "1" "Compile all .py files" \
            "2" "Deploy selected files" \
            "3" "Compile all, then deploy selected files" \
            "4" "Settings" \
            "5" "Exit" \
            3>&1 1>&2 2>&3
    )" || exit 0

    case "$MENU_CHOICE" in
        1)
            echo "=== Compiling all .py files ==="
            echo "Source: $SOURCE_DIR"
            echo "Output: $OUTPUT_DIR"
            echo "Arch:   $ARCH"
            echo

            echo "Removing old .mpy files from output folder..."
            find "$OUTPUT_DIR" -maxdepth 1 -type f -name '*.mpy' -delete

            found=0
            while IFS= read -r -d '' py_file; do
                found=1
                name="$(basename "$py_file" .py)"
                output="$OUTPUT_DIR/$name.mpy"

                echo "  $(basename "$py_file") -> $output"
                "$MPY_CROSS" -march="$ARCH" "$py_file" -o "$output"
            done < <(find "$SOURCE_DIR" -maxdepth 1 -type f -name '*.py' -print0 | sort -z)

            if [[ "$found" -eq 0 ]]; then
                echo "No .py files found directly in $SOURCE_DIR"
            fi

            echo
            echo "=== Compile complete ==="
            read -r -p "Press Enter to return to the menu..." _
            ;;

        2|3)
            # Choice 3 explicitly compiles first.
            if [[ "$MENU_CHOICE" == "3" ]]; then
                echo "=== Compiling all .py files before deployment ==="
                echo "Source: $SOURCE_DIR"
                echo "Output: $OUTPUT_DIR"
                echo "Arch:   $ARCH"
                echo

                echo "Removing old .mpy files from output folder..."
                find "$OUTPUT_DIR" -maxdepth 1 -type f -name '*.mpy' -delete

                found=0
                while IFS= read -r -d '' py_file; do
                    found=1
                    name="$(basename "$py_file" .py)"
                    output="$OUTPUT_DIR/$name.mpy"

                    echo "  $(basename "$py_file") -> $output"
                    "$MPY_CROSS" -march="$ARCH" "$py_file" -o "$output"
                done < <(find "$SOURCE_DIR" -maxdepth 1 -type f -name '*.py' -print0 | sort -z)

                if [[ "$found" -eq 0 ]]; then
                    echo "No .py files found directly in $SOURCE_DIR"
                fi

                echo
                echo "=== Compile complete; continuing to deployment ==="
            fi

            # Build checklist from output .mpy files.
            mapfile -d '' MPY_FILES < <(
                find "$OUTPUT_DIR" -maxdepth 1 -type f -name '*.mpy' -print0 | sort -z
            )

            if [[ "${#MPY_FILES[@]}" -eq 0 ]]; then
                whiptail --title "No files" \
                    --msgbox "No .mpy files were found in:\n$OUTPUT_DIR" 10 70
                continue
            fi

            OPTIONS=()
            for full_path in "${MPY_FILES[@]}"; do
                filename="$(basename "$full_path")"
                OPTIONS+=("$filename" "" "OFF")
            done

            CHOICES="$(
                whiptail --title "File Selector" \
                    --checklist \
                    "Select the .mpy files to deploy (Space = toggle, Enter = confirm):" \
                    20 80 12 \
                    "${OPTIONS[@]}" \
                    3>&1 1>&2 2>&3
            )" || {
                echo "Deployment cancelled."
                continue
            }

            # Whiptail returns quoted names. Read them safely without eval.
            mapfile -t SELECTED_FILES < <(
                printf '%s\n' "$CHOICES" |
                grep -oE '"[^"]*"' |
                sed 's/^"//; s/"$//'
            )

            if [[ "${#SELECTED_FILES[@]}" -eq 0 ]]; then
                whiptail --title "No files selected" \
                    --msgbox "No files were selected for deployment." 8 60
                continue
            fi

            echo
            echo "=== Starting deployment ==="
            echo "Target: $SSH_TARGET"
            echo "mpremote: $MPREMOTE"
            echo "Files: ${#SELECTED_FILES[@]}"
            echo

            local_files=()
            for filename in "${SELECTED_FILES[@]}"; do
                local_file="$OUTPUT_DIR/$filename"
                [[ -f "$local_file" ]] || die "Selected file does not exist: $local_file"
                local_files+=("$local_file")
            done

            # Transfer all files in one SCP invocation. This keeps each selected
            # filename as its own argument instead of treating the list as one path.
            scp "${local_files[@]}" "$SSH_TARGET:/tmp/"

            for filename in "${SELECTED_FILES[@]}"; do
                remote_tmp="/tmp/$filename"
                printf -v remote_tmp_quoted '%q' "$remote_tmp"

                echo "----------------------------------------"
                echo "Deploying: $filename"

                ssh "$SSH_TARGET" \
                    "$MPREMOTE cp $remote_tmp_quoted : && rm -f $remote_tmp_quoted"
            done

            echo "----------------------------------------"
            echo "Deployment complete."

            whiptail --title "Deployment complete" \
                --msgbox \
                "Successfully deployed ${#SELECTED_FILES[@]} file(s) to $SSH_TARGET." \
                10 70
            ;;

        4)
            SOURCE_DIR_NEW="$(
                input_box \
                    "Source folder" \
                    "Folder containing the .py files:" \
                    "$SOURCE_DIR"
            )" || continue

            OUTPUT_DIR_NEW="$(
                input_box \
                    "Output folder" \
                    "Folder where .mpy files are written:" \
                    "$OUTPUT_DIR"
            )" || continue

            MPY_CROSS_NEW="$(
                input_box \
                    "mpy-cross" \
                    "Path to the mpy-cross executable:" \
                    "$MPY_CROSS"
            )" || continue

            [[ -d "$SOURCE_DIR_NEW" ]] || {
                whiptail --title "Invalid source folder" \
                    --msgbox "Directory does not exist:\n$SOURCE_DIR_NEW" 8 70
                continue
            }

            [[ -x "$MPY_CROSS_NEW" ]] || {
                whiptail --title "Invalid mpy-cross" \
                    --msgbox "Not executable:\n$MPY_CROSS_NEW" 8 70
                continue
            }

            SOURCE_DIR="$SOURCE_DIR_NEW"
            OUTPUT_DIR="$OUTPUT_DIR_NEW"
            MPY_CROSS="$MPY_CROSS_NEW"
            SSH_TARGET_NEW="$(
                input_box \
                    "SSH target" \
                    "Remote SSH target (user@host):" \
                    "$SSH_TARGET"
            )" || continue

            MPREMOTE_NEW="$(
                input_box \
                    "mpy remote command" \
                    "Remote mpremote executable/command:" \
                    "$MPREMOTE"
            )" || continue

            SSH_TARGET="$SSH_TARGET_NEW"
            MPREMOTE="$MPREMOTE_NEW"
            mkdir -p "$OUTPUT_DIR"
            save_config
            ;;

        5)
            exit 0
            ;;
    esac
done
